# -*- coding: utf-8 -*-
"""AI_Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1907NXhBAggrvA9r3ousQ5maT5GvgKmIC
"""

df = pd.read_csv("/content/weather_forecast_data.csv")   # 🔥 replace with your file name
print(df.head())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# X = all numerical weather features
X = df[["Humidity", "Wind_Speed", "Cloud_Cover", "Pressure"]]

# y = Temperature
y = df["Temperature"]

# Train Model
# -----------------------------
model = LinearRegression()
model.fit(X, y)

# Predictions
y_pred = model.predict(X)

# Error Metrics
# -----------------------------
MAE = mean_absolute_error(y, y_pred)
MSE = mean_squared_error(y, y_pred)
RMSE = np.sqrt(MSE)
R2 = r2_score(y, y_pred)

print("---- WEATHER FORECASTING METRICS ----")
print("MAE: ", MAE)
print("MSE: ", MSE)
print("RMSE: ", RMSE)
print("R2: ", R2)

plt.figure(figsize=(10,6))
plt.plot(y.values, label="Actual Temperature", color='blue')
plt.plot(y_pred, label="Predicted Temperature", color='red')

plt.title("Actual vs Predicted Temperature (Weather Forecasting)")
plt.xlabel("Sample Index")
plt.ylabel("Temperature (°C)")

# Error box on plot
plt.text(5, max(y),
         f"MAE: {MAE:.2f}\nMSE: {MSE:.2f}\nRMSE: {RMSE:.2f}\nR2: {R2:.2f}",
         bbox=dict(facecolor='white', alpha=0.8, edgecolor='grey'),
         fontsize=10)

plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

